### ISSUE TITLE
Setting Themes in ArchCraft

### ISSUE THREAD

**Issue by darkov19** [vtmx/archcraft-themes#1]
Hey mate!

I love your work here!

I wanted to use these themes in my system. Would you please help me. Thanks!

![image](https://user-images.githubusercontent.com/49094192/187034779-61222c06-a5cf-45ac-868a-e12969ff91b5.png)

What should we pass as arguments for your custom themes? (Refer to above image. I want to know what should we pass to **set_style** function)

I appreciate  you help! Thank you!

**Comment by vtmx** [comment]
Hi darkov19, I'm glad you liked it, try to do this.

```
# add 21
chosen="$(echo -e "$options" | $rofi_cmd -p "Available themes : (21 + ∞)" -dmenu -selected-row 0)"

# before esac
$theme_21)
  set_style 'kanagawa' 'Kanagawa' 'Zafiro' 'Vimix'
  ;;
```

Arguments:
1. 'kanagawa'   Name of the file, in this case kanagawa.bash
2. 'Kanagawa'  Name show in Rofi
3. 'Zafiro'          This is the name of the icon set.
4. 'Vimix'          This is the name of the GTK theme.
